name: Bicep-StorageAccount-PrivateEndpoint

trigger:
- main

variables:
  resourceGroupName: 'rg-pcme'
  location: 'westeurope'
  azureSubscription: 'AzureConnection'
  resourcePrefix: 'bicep'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'test-service-conn-bicep-test'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az bicep build --file main.bicep'